version: '3'
services:
  Sport_tv:
    image: reklama_tracking
    build: .
    volumes:
      - /home/graph/Project/Ad_tracking_with_color_filter/videos:/Projects/Ad_tracking_with_color_filter/videos
    command: /bin/sh -c 'python3 reklama_detection.py sport_tv'
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        
  
  Kinoteatr_tv:
    image: reklama_tracking
    build: .
    volumes:
      - /home/graph/Project/Ad_tracking_with_color_filter/videos:/Projects/Ad_tracking_with_color_filter/videos
    command: /bin/sh -c 'python3 reklama_detection.py kinoteatr_tv'
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  Sevimli_tv:
    image: reklama_tracking
    build: .
    volumes:
      - /home/graph/Project/Ad_tracking_with_color_filter/videos:/Projects/Ad_tracking_with_color_filter/videos
    command: /bin/sh -c 'python3 reklama_detection.py sevimli_tv'
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  My5_tv:
    image: reklama_tracking
    build: .
    volumes:
      - /home/graph/Project/Ad_tracking_with_color_filter/videos:/Projects/Ad_tracking_with_color_filter/videos
    command: /bin/sh -c 'python3 reklama_detection.py my5_tv'
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
  
  Zor_tv:
    image: reklama_tracking
    build: .
    volumes:
      - /home/graph/Project/Ad_tracking_with_color_filter/videos:/Projects/Ad_tracking_with_color_filter/videos
    command: /bin/sh -c 'python3 reklama_detection.py zor_tv'
    environment:
      - NVIDIA_DRIVER_CAPABILITIES=all
    restart: on-failure
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]